#!/usr/bin/perl

use strict;
use warnings;

use FindBin qw($Bin);
use IO::All;

my ($image) = @ARGV;

if ($image !~ /\A[1-8]\z/)
{
    print "$Bin/error.jpg\n";
    exit(0);
}
my $io = io("$Bin/wallpapers/$image/image");

if (!$io->exists())
{
    print "$Bin/error.jpg\n";
    exit(0);
}
print $io->readlink(), "\n";
